<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\Domain\ProjectAscension.Domain\ProjectAscension.Domain.csproj" />
    <ProjectReference Include="..\..\..\packages\Contracts\ProjectAscension.Contracts\ProjectAscension.Contracts.csproj" />
    <ProjectReference Include="..\..\..\packages\Shared\ProjectAscension.Shared\ProjectAscension.Shared.csproj" />
    <ProjectReference Include="..\..\..\packages\Discovery\ProjectAscension.Discovery\ProjectAscension.Discovery.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
