// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectAscension.Api.Data;

#nullable disable

namespace ProjectAscension.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713041823_DiscoveryEconomyFix")]
    partial class DiscoveryEconomyFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NpcId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("NpcId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.BehaviorWeight", b =>
                {
                    b.Property<string>("Behavior")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Behavior");

                    b.ToTable("BehaviorWeights");

                    b.HasData(
                        new
                        {
                            Behavior = "Jump",
                            Weight = 1
                        },
                        new
                        {
                            Behavior = "Dodge",
                            Weight = 1
                        },
                        new
                        {
                            Behavior = "MeleeAttack",
                            Weight = 2
                        },
                        new
                        {
                            Behavior = "RangedAttack",
                            Weight = 2
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OriginRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRegionId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.CombatTuningSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<float>("AreaDamage")
                        .HasColumnType("real");

                    b.Property<int>("BaseDotTicks")
                        .HasColumnType("integer");

                    b.Property<float>("BeamDamage")
                        .HasColumnType("real");

                    b.Property<float>("BlockFrontArcDot")
                        .HasColumnType("real");

                    b.Property<float>("BlockReduction")
                        .HasColumnType("real");

                    b.Property<float>("ChargedAttackThreshold")
                        .HasColumnType("real");

                    b.Property<float>("ControlDurationPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("DashPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("DeliveryAreaRadius")
                        .HasColumnType("real");

                    b.Property<float>("DeliveryHitscanRadius")
                        .HasColumnType("real");

                    b.Property<float>("DeliveryProjectileGravity")
                        .HasColumnType("real");

                    b.Property<float>("DeliveryProjectileSpeed")
                        .HasColumnType("real");

                    b.Property<float>("DeliveryRange")
                        .HasColumnType("real");

                    b.Property<float>("DotDamagePerTick")
                        .HasColumnType("real");

                    b.Property<float>("FocusCostPerPoint")
                        .HasColumnType("real");

                    b.Property<float>("KnockbackPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("LeechFractionPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("PassiveBarrierReduction")
                        .HasColumnType("real");

                    b.Property<float>("PassiveLeech")
                        .HasColumnType("real");

                    b.Property<float>("PassiveShieldReduction")
                        .HasColumnType("real");

                    b.Property<float>("ProjectileDamage")
                        .HasColumnType("real");

                    b.Property<float>("ShieldPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("SlowPerMagnitude")
                        .HasColumnType("real");

                    b.Property<float>("SpreadFalloff")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CombatTuningSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaDamage = 8f,
                            BaseDotTicks = 2,
                            BeamDamage = 9f,
                            BlockFrontArcDot = 0.35f,
                            BlockReduction = 0.75f,
                            ChargedAttackThreshold = 0.7f,
                            ControlDurationPerMagnitude = 0.6f,
                            DashPerMagnitude = 2f,
                            DeliveryAreaRadius = 4f,
                            DeliveryHitscanRadius = 1.5f,
                            DeliveryProjectileGravity = 0f,
                            DeliveryProjectileSpeed = 32f,
                            DeliveryRange = 60f,
                            DotDamagePerTick = 3f,
                            FocusCostPerPoint = 4f,
                            KnockbackPerMagnitude = 4f,
                            LeechFractionPerMagnitude = 0.15f,
                            PassiveBarrierReduction = 0.08f,
                            PassiveLeech = 0.05f,
                            PassiveShieldReduction = 0.06f,
                            ProjectileDamage = 10f,
                            ShieldPerMagnitude = 12f,
                            SlowPerMagnitude = 0.15f,
                            SpreadFalloff = 0.6f
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DelegationAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IssuerActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgressCount")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RewardJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ConditionsJson = "{\"targetCount\":5,\"issuer\":\"City Watch\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = false,
                            Description = "Defeat 5 monsters in the frontier.",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Hunt",
                            RewardJson = "{\"currency\":120,\"reputation\":5}",
                            Status = "Open",
                            Title = "Cull the Beasts"
                        },
                        new
                        {
                            Id = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ConditionsJson = "{\"targetCount\":1,\"issuer\":\"Survey Office\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = false,
                            Description = "Reach the survey marker.",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Survey",
                            RewardJson = "{\"currency\":20,\"reputation\":4,\"itemKey\":\"frontier_map\",\"itemAmount\":1}",
                            Status = "Open",
                            Title = "Map the Frontier"
                        },
                        new
                        {
                            Id = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ConditionsJson = "{\"targetCount\":3,\"issuer\":\"Herbalist Guild\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = false,
                            Description = "Collect 3 samples.",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Collection",
                            RewardJson = "{\"currency\":90,\"reputation\":3}",
                            Status = "Open",
                            Title = "Gather Samples"
                        },
                        new
                        {
                            Id = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ConditionsJson = "{\"targetCount\":2,\"target\":\"elite\",\"timeLimitSeconds\":120,\"failOn\":[\"timeout\"],\"issuer\":\"Bounty Office\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = false,
                            Description = "Slay 2 elite monsters.",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Hunt",
                            RewardJson = "{\"currency\":220,\"reputation\":8}",
                            Status = "Open",
                            Title = "Elite Bounty"
                        },
                        new
                        {
                            Id = new Guid("c0000005-0000-0000-0000-000000000005"),
                            ConditionsJson = "{\"targetCount\":4,\"target\":\"elite\",\"issuer\":\"Frontier Command\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = true,
                            Description = "Slay 4 elite monsters in the deep frontier. (Hard — consider delegating.)",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Hunt",
                            RewardJson = "{\"currency\":400,\"reputation\":12}",
                            Status = "Open",
                            Title = "Deep Cull"
                        },
                        new
                        {
                            Id = new Guid("c0000006-0000-0000-0000-000000000006"),
                            ConditionsJson = "{\"targetCount\":3,\"target\":\"elite\",\"minReputation\":20,\"timeLimitSeconds\":180,\"failOn\":[\"timeout\",\"death\"],\"issuer\":\"Warden's Office\"}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelegationAllowed = false,
                            Description = "A trusted expeditionary's charge: slay 3 elites. (Requires standing.)",
                            Kind = "Task",
                            ProgressCount = 0,
                            Purpose = "Hunt",
                            RewardJson = "{\"currency\":350,\"reputation\":15}",
                            Status = "Open",
                            Title = "Frontier Warden"
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.ContractMarketAccessPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("ContractMarketAccessPoints");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.ContractRewardTuning", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("BandMaxPercent")
                        .HasColumnType("integer");

                    b.Property<int>("BandMinPercent")
                        .HasColumnType("integer");

                    b.Property<float>("BaseRewardPerCount")
                        .HasColumnType("real");

                    b.Property<float>("DifficultyScale")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ContractRewardTuning");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandMaxPercent = 150,
                            BandMinPercent = 70,
                            BaseRewardPerCount = 25f,
                            DifficultyScale = 0.4f
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Discovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiscovererActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscovererActorId");

                    b.HasIndex("RegionId");

                    b.ToTable("Discoveries");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredContextJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredProgress")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateKey")
                        .IsUnique();

                    b.ToTable("DiscoveryCandidates");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryLineage", b =>
                {
                    b.Property<Guid>("ChildDiscoveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentDiscoveryId")
                        .HasColumnType("uuid");

                    b.HasKey("ChildDiscoveryId", "ParentDiscoveryId");

                    b.HasIndex("ChildDiscoveryId");

                    b.HasIndex("ParentDiscoveryId");

                    b.ToTable("DiscoveryLineages");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscoveryCandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryCandidateId");

                    b.HasIndex("ActorId", "DiscoveryCandidateId")
                        .IsUnique();

                    b.ToTable("DiscoveryProgresses");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoverySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("BehaviorProfileJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<string>("BehaviorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ComposedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextTagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DiscoveryId")
                        .HasColumnType("uuid");

                    b.Property<string>("EffectGraphJson")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InvocationComboJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manifestation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PowerBudget")
                        .HasColumnType("integer");

                    b.Property<int?>("PowerCost")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryBehavior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("DiscoverySkills");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryTuningSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetBase")
                        .HasColumnType("integer");

                    b.Property<double>("BudgetGrowth")
                        .HasColumnType("double precision");

                    b.Property<int>("BudgetMax")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetMin")
                        .HasColumnType("integer");

                    b.Property<int>("ChainWeight")
                        .HasColumnType("integer");

                    b.Property<int>("CombinationSynergy")
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrencyWeight")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultBehaviorWeight")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultFactorWeight")
                        .HasColumnType("integer");

                    b.Property<int>("EpicScore")
                        .HasColumnType("integer");

                    b.Property<int>("FireThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("FuseWeight")
                        .HasColumnType("integer");

                    b.Property<int>("KnowledgeDepthWeight")
                        .HasColumnType("integer");

                    b.Property<int>("LegendaryScore")
                        .HasColumnType("integer");

                    b.Property<int>("PersistenceWeight")
                        .HasColumnType("integer");

                    b.Property<int>("RareScore")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceWeight")
                        .HasColumnType("integer");

                    b.Property<int>("UncommonScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DiscoveryTuningSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BudgetBase = 6,
                            BudgetGrowth = 2.3999999999999999,
                            BudgetMax = 40,
                            BudgetMin = 10,
                            ChainWeight = 6,
                            CombinationSynergy = 15,
                            ConcurrencyWeight = 12,
                            DefaultBehaviorWeight = 1,
                            DefaultFactorWeight = 0,
                            EpicScore = 338,
                            FireThreshold = 100,
                            FuseWeight = 25,
                            KnowledgeDepthWeight = 12,
                            LegendaryScore = 506,
                            PersistenceWeight = 5,
                            RareScore = 225,
                            SequenceWeight = 15,
                            UncommonScore = 150
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.FactorWeight", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("FactorWeights");

                    b.HasData(
                        new
                        {
                            Key = "waterfall",
                            Category = "Environment",
                            Weight = 10
                        },
                        new
                        {
                            Key = "ice_wall",
                            Category = "Environment",
                            Weight = 10
                        },
                        new
                        {
                            Key = "crystal_desert",
                            Category = "Environment",
                            Weight = 12
                        },
                        new
                        {
                            Key = "jungle",
                            Category = "Environment",
                            Weight = 8
                        },
                        new
                        {
                            Key = "sword",
                            Category = "Equipment",
                            Weight = 4
                        },
                        new
                        {
                            Key = "bow",
                            Category = "Equipment",
                            Weight = 4
                        },
                        new
                        {
                            Key = "pistol",
                            Category = "Equipment",
                            Weight = 4
                        },
                        new
                        {
                            Key = "catalyst",
                            Category = "Equipment",
                            Weight = 6
                        },
                        new
                        {
                            Key = "fire",
                            Category = "Knowledge",
                            Weight = 8
                        },
                        new
                        {
                            Key = "compression",
                            Category = "Knowledge",
                            Weight = 8
                        },
                        new
                        {
                            Key = "wind",
                            Category = "Knowledge",
                            Weight = 8
                        },
                        new
                        {
                            Key = "monster:melee",
                            Category = "Monster",
                            Weight = 6
                        },
                        new
                        {
                            Key = "monster:ranged",
                            Category = "Monster",
                            Weight = 8
                        },
                        new
                        {
                            Key = "monster:elite",
                            Category = "Monster",
                            Weight = 14
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.ItemDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("ItemDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "hide",
                            BuyPrice = 16,
                            Description = "Tough hide from frontier beasts — raises shelters and armor.",
                            DisplayName = "Beast Hide",
                            SellPrice = 8
                        },
                        new
                        {
                            Key = "feather",
                            BuyPrice = 20,
                            Description = "Light feathers prized in the city markets.",
                            DisplayName = "Sky Feather",
                            SellPrice = 10
                        },
                        new
                        {
                            Key = "core",
                            BuyPrice = 90,
                            Description = "A volatile core torn from an elite — fortifies the outpost's defenses.",
                            DisplayName = "Elite Core",
                            SellPrice = 40
                        },
                        new
                        {
                            Key = "frontier_map",
                            BuyPrice = 0,
                            Description = "Charted ground beyond the wall. Ink, hide, and someone's survival.",
                            DisplayName = "Frontier Map",
                            SellPrice = 0
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiscoveryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerActorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryId")
                        .IsUnique();

                    b.HasIndex("OwnerActorId");

                    b.ToTable("Knowledge");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Loadout", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeftItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RightItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActorId");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SpawnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.MonsterDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<float>("AggroRange")
                        .HasColumnType("real");

                    b.Property<float>("AttackCooldown")
                        .HasColumnType("real");

                    b.Property<float>("AttackRange")
                        .HasColumnType("real");

                    b.Property<float>("AttackWindup")
                        .HasColumnType("real");

                    b.Property<float>("Damage")
                        .HasColumnType("real");

                    b.Property<int>("DropAmount")
                        .HasColumnType("integer");

                    b.Property<string>("DropItemKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("MaxHealth")
                        .HasColumnType("real");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<float>("ProjectileSpeed")
                        .HasColumnType("real");

                    b.Property<float>("Scale")
                        .HasColumnType("real");

                    b.HasKey("Key");

                    b.ToTable("MonsterDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "melee",
                            AggroRange = 25f,
                            AttackCooldown = 1f,
                            AttackRange = 2f,
                            AttackWindup = 0.35f,
                            Damage = 8f,
                            DropAmount = 2,
                            DropItemKey = "hide",
                            MaxHealth = 40f,
                            MoveSpeed = 3.5f,
                            ProjectileSpeed = 0f,
                            Scale = 1f
                        },
                        new
                        {
                            Key = "ranged",
                            AggroRange = 30f,
                            AttackCooldown = 1.5f,
                            AttackRange = 14f,
                            AttackWindup = 0.5f,
                            Damage = 6f,
                            DropAmount = 2,
                            DropItemKey = "feather",
                            MaxHealth = 25f,
                            MoveSpeed = 2f,
                            ProjectileSpeed = 18f,
                            Scale = 1f
                        },
                        new
                        {
                            Key = "elite",
                            AggroRange = 35f,
                            AttackCooldown = 1.2f,
                            AttackRange = 18f,
                            AttackWindup = 0.65f,
                            Damage = 14f,
                            DropAmount = 1,
                            DropItemKey = "core",
                            MaxHealth = 120f,
                            MoveSpeed = 2.5f,
                            ProjectileSpeed = 24f,
                            Scale = 1.6f
                        },
                        new
                        {
                            Key = "guardian",
                            AggroRange = 45f,
                            AttackCooldown = 1.4f,
                            AttackRange = 20f,
                            AttackWindup = 0.9f,
                            Damage = 45f,
                            DropAmount = 3,
                            DropItemKey = "core",
                            MaxHealth = 600f,
                            MoveSpeed = 3.2f,
                            ProjectileSpeed = 26f,
                            Scale = 2.6f
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.MonsterSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DropsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonsterSpecies");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.NPC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentRegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("NPCs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            Alive = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Quartermaster Hale",
                            Role = "Shopkeeper"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            Alive = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Serjeant Bran",
                            Role = "Guard"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            Alive = true,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeRegionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Survey Clerk Mira",
                            Role = "Contract Clerk"
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.PlayerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<float>("DodgeDuration")
                        .HasColumnType("real");

                    b.Property<float>("DodgeSpeed")
                        .HasColumnType("real");

                    b.Property<float>("FocusRegenPerSecond")
                        .HasColumnType("real");

                    b.Property<float>("Gravity")
                        .HasColumnType("real");

                    b.Property<float>("JumpVelocity")
                        .HasColumnType("real");

                    b.Property<float>("MaxFocus")
                        .HasColumnType("real");

                    b.Property<float>("MaxHealth")
                        .HasColumnType("real");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PlayerDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DodgeDuration = 0.2f,
                            DodgeSpeed = 12f,
                            FocusRegenPerSecond = 15f,
                            Gravity = 20f,
                            JumpVelocity = 6f,
                            MaxFocus = 100f,
                            MaxHealth = 100f,
                            MoveSpeed = 5f
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.PlayerProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer");

                    b.Property<string>("ResourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoldKnowledgeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 0,
                            Reputation = 0,
                            ResourcesJson = "{}",
                            SoldKnowledgeJson = "[]"
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("EnvironmentTagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DefensePoints")
                        .HasColumnType("integer");

                    b.Property<int>("MarketPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ShelterPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Settlements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefensePoints = 0,
                            MarketPoints = 0,
                            Name = "Frontier Outpost",
                            ShelterPoints = 0
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.WeaponDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<float>("ChargeTime")
                        .HasColumnType("real");

                    b.Property<float>("Cooldown")
                        .HasColumnType("real");

                    b.Property<float>("Damage")
                        .HasColumnType("real");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<float>("MaxChargeMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("ProjectileGravity")
                        .HasColumnType("real");

                    b.Property<float>("ProjectileSpeed")
                        .HasColumnType("real");

                    b.Property<float>("Range")
                        .HasColumnType("real");

                    b.Property<int>("SlotType")
                        .HasColumnType("integer");

                    b.Property<float>("SpreadMax")
                        .HasColumnType("real");

                    b.Property<float>("SpreadMin")
                        .HasColumnType("real");

                    b.Property<float>("SpreadPerShot")
                        .HasColumnType("real");

                    b.Property<float>("SpreadRecovery")
                        .HasColumnType("real");

                    b.HasKey("Key");

                    b.ToTable("WeaponDefinitions");

                    b.HasData(
                        new
                        {
                            Key = "sword",
                            ChargeTime = 0f,
                            Cooldown = 0.5f,
                            Damage = 25f,
                            DisplayName = "Sword",
                            EquipmentType = 0,
                            MaxChargeMultiplier = 1f,
                            ProjectileGravity = 0f,
                            ProjectileSpeed = 0f,
                            Range = 2.2f,
                            SlotType = 2,
                            SpreadMax = 0f,
                            SpreadMin = 0f,
                            SpreadPerShot = 0f,
                            SpreadRecovery = 0f
                        },
                        new
                        {
                            Key = "bow",
                            ChargeTime = 0.8f,
                            Cooldown = 0.6f,
                            Damage = 18f,
                            DisplayName = "Bow",
                            EquipmentType = 3,
                            MaxChargeMultiplier = 2.5f,
                            ProjectileGravity = 9.8f,
                            ProjectileSpeed = 28f,
                            Range = 60f,
                            SlotType = 3,
                            SpreadMax = 0f,
                            SpreadMin = 0f,
                            SpreadPerShot = 0f,
                            SpreadRecovery = 0f
                        },
                        new
                        {
                            Key = "pistol",
                            ChargeTime = 0f,
                            Cooldown = 0.25f,
                            Damage = 12f,
                            DisplayName = "Pistol",
                            EquipmentType = 4,
                            MaxChargeMultiplier = 1f,
                            ProjectileGravity = 0f,
                            ProjectileSpeed = 0f,
                            Range = 60f,
                            SlotType = 2,
                            SpreadMax = 9f,
                            SpreadMin = 1f,
                            SpreadPerShot = 1.4f,
                            SpreadRecovery = 7f
                        },
                        new
                        {
                            Key = "catalyst",
                            ChargeTime = 0f,
                            Cooldown = 0.8f,
                            Damage = 22f,
                            DisplayName = "Arcane Catalyst",
                            EquipmentType = 5,
                            MaxChargeMultiplier = 1f,
                            ProjectileGravity = 0f,
                            ProjectileSpeed = 18f,
                            Range = 50f,
                            SlotType = 2,
                            SpreadMax = 0f,
                            SpreadMin = 0f,
                            SpreadPerShot = 0f,
                            SpreadRecovery = 0f
                        },
                        new
                        {
                            Key = "shield",
                            ChargeTime = 0f,
                            Cooldown = 0f,
                            Damage = 0f,
                            DisplayName = "Kite Shield",
                            EquipmentType = 2,
                            MaxChargeMultiplier = 1f,
                            ProjectileGravity = 0f,
                            ProjectileSpeed = 0f,
                            Range = 0f,
                            SlotType = 0,
                            SpreadMax = 0f,
                            SpreadMin = 0f,
                            SpreadPerShot = 0f,
                            SpreadRecovery = 0f
                        });
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Actor", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Character", "Character")
                        .WithOne("Actor")
                        .HasForeignKey("ProjectAscension.Domain.Entities.Actor", "CharacterId");

                    b.HasOne("ProjectAscension.Domain.Entities.NPC", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId");

                    b.Navigation("Character");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Character", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Region", "CurrentRegion")
                        .WithMany()
                        .HasForeignKey("CurrentRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentRegion");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.ContractMarketAccessPoint", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Discovery", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Actor", "Discoverer")
                        .WithMany()
                        .HasForeignKey("DiscovererActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAscension.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discoverer");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryLineage", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Discovery", "Child")
                        .WithMany()
                        .HasForeignKey("ChildDiscoveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectAscension.Domain.Entities.Discovery", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentDiscoveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoveryProgress", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAscension.Domain.Entities.DiscoveryCandidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("DiscoveryCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.DiscoverySkill", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Discovery", "Discovery")
                        .WithMany()
                        .HasForeignKey("DiscoveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discovery");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Item", "Item")
                        .WithOne()
                        .HasForeignKey("ProjectAscension.Domain.Entities.Equipment", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Knowledge", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Discovery", "Discovery")
                        .WithMany()
                        .HasForeignKey("DiscoveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAscension.Domain.Entities.Actor", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discovery");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Loadout", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Actor", "Actor")
                        .WithOne()
                        .HasForeignKey("ProjectAscension.Domain.Entities.Loadout", "ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Monster", b =>
                {
                    b.HasOne("ProjectAscension.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAscension.Domain.Entities.MonsterSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ProjectAscension.Domain.Entities.Character", b =>
                {
                    b.Navigation("Actor");
                });
#pragma warning restore 612, 618
        }
    }
}
